_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
                - 71
                - 98
                - 100
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.11
            "6": 4.51.3
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 2
learning_rate:
    value: 0.0001
lora_alpha:
    value: 32
lora_dropout:
    value: 0.1
num_train_epochs:
    value: 15
r:
    value: 8
